### ISSUE TITLE
Issue compiling in Linux Mint 21.2

### ISSUE THREAD

**Issue by ghost** [cloudofoz/raylib-media#3] opened 2024-11-18 21:55 UTC
Hi, I'm having an issue compiling the project using GCC.

```
rmedia.c:709:33: error: unknown type name ‘AVChannelLayout’
  709 |                                 AVChannelLayout out_ch_layout;
      |                                 ^~~~~~~~~~~~~~~
rmedia.c:710:33: warning: implicit declaration of function ‘av_channel_layout_default’ [-Wimplicit-function-declaration]
  710 |                                 av_channel_layout_default(&out_ch_layout, MEDIA.audioOutputChannels);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
rmedia.c:713:39: warning: implicit declaration of function ‘swr_alloc_set_opts2’; did you mean ‘swr_alloc_set_opts’? [-Wimplicit-function-declaration]
  713 |                                 ret = swr_alloc_set_opts2(&ctx->swrContext,
      |                                       ^~~~~~~~~~~~~~~~~~~
      |                                       swr_alloc_set_opts
rmedia.c:717:52: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
  717 |                                         &codecCtx->ch_layout,  // Input channel layout
      |                                                    ^~~~~~~~~
      |                                                    channel_layout
rmedia.c:723:33: warning: implicit declaration of function ‘av_channel_layout_uninit’; did you mean ‘av_get_channel_layout_string’? [-Wimplicit-function-declaration]
  723 |                                 av_channel_layout_uninit(&out_ch_layout);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                 av_get_channel_layout_string
rmedia.c:761:141: error: ‘AVCodecParameters’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
  761 |  channels, sample rate %d", fileName, localCodecParameters->ch_layout.nb_channels, localCodecParameters->sample_rate);
      |                                                             ^~~~~~~~~
      |                                                             channel_layout
```
I ran `sudo apt install libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev` exactly as on the README, and then ran `gcc rmedia.c -lraylib -lavcodec -lavformat -lavutil -lswresample -lswscale`

Let me know if I should give any further information about my system.

**Comment by cloudofoz** [comment] 2024-11-18 22:26
Hi @sockentrocken,

Thank you for reporting this issue and for providing the details! Based on the information you’ve shared, it seems the issue might be related to the version of FFmpeg libraries available on Linux Mint 21.2.

Linux Mint 21.2 is based on Ubuntu 22.04 LTS, which could provide older versions of FFmpeg in its repositories.

For reference, I tested the library with **Ubuntu 24.10** and **FFmpeg 7.x** and confirmed it works as expected with the FFmpeg versions available on that platform.

In the future, I could provide a compatibility patch for older FFmpeg versions, but I will need some time to set up the environment for that. Meanwhile, you could try updating FFmpeg to a newer version.

Let me know if you would like to try!

Best regards,

C.

**Comment by ghost** [comment] 2024-11-18 23:37
Wow...yeah, my FFMPEG version is quite old (4.4.2), I just realized that. Sorry for the inconvenience, I'll make sure to update FFMPEG and report back.

**Comment by ghost** [comment] 2024-11-18 23:53
Yup, that did it. Also had to add `-lm` at the end of my build command, for some reason.

**Comment by cloudofoz** [comment] 2024-11-19 00:05
I'm glad to hear it worked! Thank you for testing and reporting back. The need for `-lm` might be due to certain math functions being used; I'll make a note in the README about that to help others who might encounter the same situation.

Closing this issue now, but feel free to reach out if you encounter any further problems!

Best regards,
C.

**Closed as completed by cloudofoz** 2024-11-19 00:05 UTC
